#!/usr/bin/env python
# -*- encoding: utf-8 -*-
##############################################################################
#
#    Asterisk Screen Pop module for OpenERP
#    Copyright (C) 2012 Les Green <l.green@valuedecision.com>
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Affero General Public License as
#    published by the Free Software Foundation, either version 3 of the
#    License, or (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Affero General Public License for more details.
#
#    You should have received a copy of the GNU Affero General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
##############################################################################
import sys
from twisted.python import log
from twisted.internet import reactor
from autobahn.wamp import WampServerFactory
from callmanager.openerp_config import OpenERPConfig
from callmanager.openerp_wamp_server_protocol import OpenERPWampServerProtocol

if __name__=='__main__':
    conf = OpenERPConfig().get_ws_connection()
    sys.stdout = open(conf['log-file'],"a")
    
    log.startLogging(sys.stdout)
    factory = WampServerFactory(conf['uri'], debug=conf['debug'])
    factory.protocol = OpenERPWampServerProtocol
    reactor.listenTCP(int(conf['ws-port']), factory)
    log.msg("Web Socket Server Reactor Running")
    reactor.run()
    
    sys.stdout.close()
    sys.stdout = sys.__stdout__
    